package w3cp.model.status.charging;

import lombok.Getter;
import lombok.Setter;

import javax.annotation.Nullable;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Getter
@Setter
public class ChargeSession {

  /**
   * Identifier of the current or last charging session on this port.
   * May be generated by CP or backend; must be stable for the lifetime of this session.
   * Nullable; null = "no session / not reported".
   */
  @Nullable private UUID sessionId;

  @Nullable private Instant createdAt;           // when session started
  @Nullable private Instant energyFlowStartedAt; // when first energy started flowing
  @Nullable private Instant lastUpdateAt;        // last session-related change
  @Nullable private Instant endedAt;             // when session ended, if applicable

  // ---------------------------------------------------------------------
  // Per-session energy counters OWNED by the CP
  // ---------------------------------------------------------------------

  /**
   * Energy delivered from CP to vehicle during this session, in kWh.
   * Monotonically increasing from 0 for the session; CP should never decrease it.
   *
   * Backend MUST treat this as the canonical per-session "to vehicle" energy.
   * It is NOT required to compute this from CP lifetime meters.
   */
  @Nullable private Double energyToVehicleKWh;

  /**
   * Energy received by CP from vehicle during this session, in kWh.
   * Monotonically increasing from 0 for the session.
   *
   * Backend MUST treat this as the canonical per-session "from vehicle" energy.
   */
  @Nullable private Double energyFromVehicleKWh;

  // ---------------------------------------------------------------------
  // Optional anchors to long-lived meters (for audit / reconciliation)
  // ---------------------------------------------------------------------

  /**
   * Snapshot of energyImportKWh when the session started, if CP tracks it.
   * This is for audit/forensics only, not required for normal billing logic.
   */
  @Nullable private Double meterImportAtStartKWh;

  /**
   * Snapshot of energyExportKWh when the session started, if CP tracks it.
   */
  @Nullable private Double meterExportAtStartKWh;

  /**
   * Session state (independent of OCPP transaction semantics).
   * null and SessionState.unknown SHOULD be treated equivalently.
   */
  @Nullable private SessionState sessionState;

  /**
   * Optional reason when the session is completed or faulted.
   * Nullable; null = "not reported".
   */
  @Nullable private EndReason endReason;

  // ---------------------------------------------------------------------
  // Authorization info for THIS session
  // ---------------------------------------------------------------------

  /**
   * How this session is/was authorized from the CP's point of view.
   * Nullable; null = "no auth concept / free charging / not reported".
   *
   * This does NOT contain billing/account information – only what the CP
   * and backend exchanged about authorization flow and what was presented.
   */
  @Nullable private Authorization authorization;

  // =====================================================================
  // NESTED TYPES
  // =====================================================================

  public enum SessionState {
    idle,       // no active session (sessionId likely null)
    pending,    // plug/handshake, not yet stable
    active,     // energyToVehicle/energyFromVehicle increasing
    paused,     // logically ongoing but power is zero
    completed,  // ended normally
    faulted,    // ended due to error
    unknown
  }

  public enum EndReason {
    vehicleUnplugged,
    cpFault,
    backendCommand,
    powerConstraint,
    timeout,
    gridEvent,
    unknown
  }

  // ───────────────── Authorization section ─────────────────

  @Getter
  @Setter
  public static class Authorization {

    /**
     * Where we are in the authorization flow for this session.
     * This is the CP/backend view of "waiting / decided / free".
     */
    @Nullable private AuthFlowState flowState;

    /**
     * When the CP first started asking for an auth decision for this session.
     * Nullable; null = "not requested / free / not reported".
     */
    @Nullable private Instant requestedAt;

    /**
     * Decision info (who decided and why), once known.
     * Nullable while still waiting.
     */
    @Nullable private Decision decision;

    /**
     * All things presented during this session:
     * - RFID card UIDs
     * - app/QR user starts
     * - vehicle identities (PnC, DID-PnC)
     * - backend/operator remote start
     *
     * "used" inside Instrument marks which one(s) actually contributed
     * to the decision.
     */
    @Nullable private List<Instrument> instruments;
  }

  @Getter
  @Setter
  public static class Decision {
    @Nullable private DecisionSource source;  // e.g. implicitFree, cp, backend
    @Nullable private String reason;          // human-readable: "free mode", "local whitelist", "backend app auth"
    @Nullable private Instant decidedAt;      // when the yes/no decision was made
  }

  @Getter
  @Setter
  public static class Instrument {
    @Nullable private InstrumentType type;   // card, vehicle, app, backend, roaming, test, other
    @Nullable private String rawId;          // as seen by CP/backend: RFID UID, userId, vin/did, etc.
    @Nullable private String label;          // nice for UI/logs: "Alice's card", "Fleet car 3"
    @Nullable private Instant presentedAt;   // when this was presented
    @Nullable private Boolean used;          // true if this instrument was actually used to authorize; null = not reported
  }

  public enum AuthFlowState {
    noneRequired,         // CP/backend decided no auth needed (free/implicit)
    waitingForInput,     // CP expects card/app/vehicle, nothing usable yet
    waitingForBackend,   // something presented, waiting for backend yes/no
    authorized,            // authorized; session may or may not have energy yet
    denied,                // explicitly denied
    expired,               // auth window closed / timeout
    unknown
  }

  public enum DecisionSource {
    implicitFree,   // charging allowed without any auth
    cp,             // CP local logic (whitelist/blacklist/offline)
    backend         // W3CP backend decided
  }

  public enum InstrumentType {
    card,       // RFID / NFC card or fob
    vehicle,    // PnC / DID-PnC / vehicle identity
    app,        // mobile/web/QR based start
    backend,    // operator console / API remote start
    roaming,    // external EMSP token
    test,       // test/demo mode
    other
  }
}